{
	"msg":"\u64CD\u4F5C\u6210\u529F\uFF01",
	"code":"200",
	"data":{
		"age":"",
		"bedNumber":"001",
		"currentDate":"2019-07-17 17:02:19",
		"currentWardName":"\u4E00\u75C5\u533A",
		"dynamicFiled1":"213123",
		"dynamicFiled2":"werwe\u6E29\u67D4\u5582",
		"entryTime":"2019-06-01 10:10:19",
		"id":"",
		"inpNumber":"ZY20190415003",
		"lvhTime":"",
		"modifer":"",
		"modifyDate":"",
		"patientName":"\u9648\u56FD\u5FBD",
		"printBedNumber":"",
		"printWardName":"",
		"record":[
			{
				"allergyMedication":"",
				"bloodPressure":{
					"1":{
						"systolic":"124",
						"diastolic":"88"
					},
					"2":{
						"diastolic":"98",
						"systolic":"124"
					},
					"3":{
						"diastolic":"83",
						"systolic":"114"
					}
				},
				"breathe":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"dynamic1":"",
				"dynamic2":"",
				"formComment":{
					"1":"",
					"2":"\u8BD5\u4E00\u4E0B\u554A",
					"3":"\u5165\u9662\u5341\u65F6\u5341\u5206",
					"4":"",
					"5":"",
					"6":""
				},
				"heartRate":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"height":"",
				"id":"",
				"inpDay":"1",
				"modifer":"",
				"modifyDate":"",
				"painScore":{
					"1":"4",
					"2":"3",
					"3":"4",
					"4":"2",
					"5":"",
					"6":""
				},
				"physicalCooling":{
					"1":"",
					"2":"",
					"3":"",
					"4":"37.6",
					"5":"",
					"6":""
				},
				"pulse":{
					"1":"88",
					"2":"94",
					"3":"82",
					"4":"124",
					"5":"92",
					"6":""
				},
				"recordDate":"2019-06-01 00:00:00",
				"stool":"",
				"surgeryDay":"",
				"temperature":{
					"1":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u53E3\u6E29",
						"value":"38.6"
					},
					"2":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"36.8"
					},
					"3":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u65AD\u70B9",
						"value":"37.4"
					},
					"4":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"38.9"
					},
					"5":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"37.4"
					},
					"6":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					}
				},
				"weight":""
			},
			{
				"allergyMedication":"",
				"bloodPressure":{
					"1":{
						"diastolic":"",
						"systolic":""
					},
					"2":{
						"diastolic":"",
						"systolic":""
					},
					"3":{
						"diastolic":"",
						"systolic":""
					}
				},
				"breathe":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"dynamic1":"",
				"dynamic2":"",
				"formComment":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"heartRate":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"height":"",
				"id":"",
				"inpDay":"2",
				"modifer":"",
				"modifyDate":"",
				"painScore":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"physicalCooling":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"pulse":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"recordDate":"2019-06-02 00:00:00",
				"stool":"",
				"surgeryDay":"",
				"temperature":{
					"1":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"2":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"3":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"4":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"5":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"6":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					}
				},
				"weight":""
			},
			{
				"allergyMedication":"",
				"bloodPressure":{
					"1":{
						"diastolic":"",
						"systolic":""
					},
					"2":{
						"diastolic":"",
						"systolic":""
					},
					"3":{
						"diastolic":"",
						"systolic":""
					}
				},
				"breathe":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"dynamic1":"sdfwe qwer",
				"dynamic2":"",
				"formComment":{
					"1":"",
					"2":"",
					"3":"\u624B\u672F",
					"4":"",
					"5":"",
					"6":""
				},
				"heartRate":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"height":"",
				"id":"",
				"inpDay":"3",
				"modifer":"",
				"modifyDate":"",
				"painScore":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"physicalCooling":{
					"1":"",
					"2":"",
					"3":"",
					"4":"37.5",
					"5":"",
					"6":""
				},
				"pulse":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"recordDate":"2019-06-03 00:00:00",
				"stool":"E",
				"surgeryDay":"",
				"temperature":{
					"1":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u53E3\u6E29",
						"value":"36.0"
					},
					"2":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"37.5"
					},
					"3":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"38.2"
					},
					"4":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"38.9"
					},
					"5":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"37.6"
					},
					"6":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"37.5"
					}
				},
				"weight":""
			},
			{
				"allergyMedication":"",
				"bloodPressure":{
					"1":{
						"diastolic":"",
						"systolic":""
					},
					"2":{
						"diastolic":"",
						"systolic":""
					},
					"3":{
						"diastolic":"",
						"systolic":""
					}
				},
				"breathe":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"dynamic1":"",
				"dynamic2":"",
				"formComment":{
					"1":"",
					"2":"",
					"3":"\u624B\u672F2",
					"4":"",
					"5":"",
					"6":""
				},
				"heartRate":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"height":"",
				"id":"",
				"inpDay":"4",
				"modifer":"",
				"modifyDate":"",
				"painScore":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"physicalCooling":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"pulse":{
					"1":"87",
					"2":"98",
					"3":"86",
					"4":"78",
					"5":"85",
					"6":"78"
				},
				"recordDate":"2019-06-04 00:00:00",
				"stool":"",
				"surgeryDay":"1",
				"temperature":{
					"1":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"36.8"
					},
					"2":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"37.8"
					},
					"3":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"35.0"
					},
					"4":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"37.8"
					},
					"5":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"36.2"
					},
					"6":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					}
				},
				"weight":""
			},
			{
				"allergyMedication":"",
				"bloodPressure":{
					"1":{
						"diastolic":"",
						"systolic":""
					},
					"2":{
						"diastolic":"",
						"systolic":""
					},
					"3":{
						"diastolic":"",
						"systolic":""
					}
				},
				"breathe":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"dynamic1":"\u8BF7\u95EE\u8BF7\u95EE",
				"dynamic2":"\u62A2\u5B8C",
				"formComment":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"heartRate":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"height":"",
				"id":"",
				"inpDay":"5",
				"modifer":"",
				"modifyDate":"",
				"painScore":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"physicalCooling":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"pulse":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"recordDate":"2019-06-05 00:00:00",
				"stool":"",
				"surgeryDay":"1\/2",
				"temperature":{
					"1":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"37.8"
					},
					"2":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"38.2"
					},
					"3":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"38.2"
					},
					"4":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"38.4"
					},
					"5":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"\u814B\u6E29",
						"value":"37.8"
					},
					"6":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					}
				},
				"weight":""
			},
			{
				"allergyMedication":"",
				"bloodPressure":{
					"1":{
						"diastolic":"",
						"systolic":""
					},
					"2":{
						"diastolic":"",
						"systolic":""
					},
					"3":{
						"diastolic":"",
						"systolic":""
					}
				},
				"breathe":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"dynamic1":"\u4E00\u4E8C\u4E09\u56DB\u4E94\u516D\u4E03\u516B",
				"dynamic2":"",
				"formComment":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"heartRate":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"height":"",
				"id":"",
				"inpDay":"6",
				"modifer":"",
				"modifyDate":"",
				"painScore":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"physicalCooling":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"pulse":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"recordDate":"2019-06-06 00:00:00",
				"stool":"",
				"surgeryDay":"2\/3",
				"temperature":{
					"1":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"2":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"3":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"4":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"5":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"6":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					}
				},
				"weight":""
			},
			{
				"allergyMedication":"",
				"bloodPressure":{
					"1":{
						"diastolic":"",
						"systolic":""
					},
					"2":{
						"diastolic":"",
						"systolic":""
					},
					"3":{
						"diastolic":"",
						"systolic":""
					}
				},
				"breathe":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"dynamic1":"wwer werwwe wer",
				"dynamic2":"wewe wewerw",
				"formComment":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"heartRate":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"height":"",
				"id":"",
				"inpDay":"7",
				"modifer":"",
				"modifyDate":"",
				"painScore":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"physicalCooling":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"pulse":{
					"1":"",
					"2":"",
					"3":"",
					"4":"",
					"5":"",
					"6":""
				},
				"recordDate":"2019-06-07 00:00:00",
				"stool":"",
				"surgeryDay":"3\/4",
				"temperature":{
					"1":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"2":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"3":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"4":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"5":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					},
					"6":{
						"id":"",
						"modifer":"",
						"modifyDate":"",
						"name":"",
						"value":""
					}
				},
				"weight":""
			}
		],
		"sex":""
	}
}